### ISSUE TITLE
[Security] Integrate Trivy for vulnerability scanning

### ISSUE THREAD

**Issue by stormcat24** [nandemo-ya/kecs#256]
## Overview

Integrate [Trivy](https://github.com/aquasecurity/trivy) vulnerability scanner into KECS to enhance security posture by scanning container images, dependencies, and infrastructure as code.

## Background

Trivy is a comprehensive security scanner that can detect:
- OS package vulnerabilities (Alpine, RHEL, CentOS, etc.)
- Language-specific package vulnerabilities (Go modules, npm, pip, etc.)
- Container image vulnerabilities
- Infrastructure as Code (IaC) misconfigurations
- Sensitive information and secrets

### 1. CI/CD Integration
- [ ] Add Trivy to GitHub Actions workflow
- [ ] Scan Docker images before push
- [ ] Scan Go dependencies on each PR
- [ ] Fail builds on critical vulnerabilities

### 2. Development Workflow
- [ ] Add Makefile target for local scanning
- [ ] Pre-commit hook for security scanning
- [ ] Integration with VS Code/IDE

### 3. Runtime Scanning (Future Enhancement)
- [ ] Scan task definition images before deployment
- [ ] Provide vulnerability reports via API
- [ ] Optional webhook for security alerts

### GitHub Actions Integration
```yaml
- name: Run Trivy vulnerability scanner
  uses: aquasecurity/trivy-action@master
  with:
    image-ref: 'kecs:latest'
    format: 'sarif'
    output: 'trivy-results.sarif'
    severity: 'CRITICAL,HIGH'
```

### Makefile Target
```makefile
.PHONY: security-scan
security-scan:
    trivy image kecs:latest
    trivy fs --security-checks vuln,config .
    trivy repo .
```

### Configuration File (.trivy.yaml)
```yaml
scan:
  security-checks:
    - vuln
    - config
    - secret
severity:
  - CRITICAL
  - HIGH
  - MEDIUM
ignore-unfixed: true
```

## Benefits

1. **Early Detection**: Identify vulnerabilities before production
2. **Compliance**: Meet security requirements and best practices
3. **Automated**: No manual security review needed
4. **Comprehensive**: Covers multiple vulnerability types
5. **Developer-Friendly**: Fast scans with clear reports

## Success Criteria

- [ ] All Docker images scanned before release
- [ ] Go dependencies checked on every PR
- [ ] Zero critical vulnerabilities in production images
- [ ] Security scan results available in PR checks
- [ ] Documentation for security practices

## References

- [Trivy Documentation](https://aquasecurity.github.io/trivy/)
- [Trivy GitHub Action](https://github.com/aquasecurity/trivy-action)
- [OWASP Container Security](https://owasp.org/www-project-docker-security/)
